// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import 'dotenv/config';
// import { defineConfig } from 'prisma/config';

// export default defineConfig({
//   schema: 'prisma/schema.prisma',
//   migrations: {
//     path: 'prisma/migrations',
//   },
//   datasource: {
//     // In Prisma 7+, the datasource URL belongs in `prisma.config.ts` rather than
//     // the schema file. This lets the CLI and Migrate read the connection string
//     // from env while keeping the schema datasource free of `url`.
//     // At runtime, `PrismaClient` should be constructed with either an `adapter`
//     // for a direct DB connection or `accelerateUrl` for Prisma Accelerate.
//     url: process.env['DATABASE_URL'],
//   },
// });

import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  datasource: {
    url: env('DATABASE_URL'),
    // shadowDatabaseUrl: env('SHADOW_DATABASE_URL'),
  },
});
